services:
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app/src
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/.env:/app/.env

  mongodb:
    image: mongo:7-jammy
    ports:
      - "27017:27017"
    command: mongod --noauth
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
