import { create } from 'zustand'
import { persist, createJSONStorage } from 'zustand/middleware'

export type Language = 'en' | 'ru'

interface LanguageState {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string, params?: Record<string, string>) => string
}

// Translation dictionaries
const translations = {
  en: {
    // Navigation
    'nav.features': 'Features',
    'nav.howItWorks': 'How It Works',
    'nav.pricing': 'Pricing',
    'nav.signIn': 'Sign in',
    'nav.startForFree': 'Start for free',
    'nav.back': 'Back',
    
    // Landing page - Hero
    'landing.hero.title': 'The next gen of data analysis.',
    'landing.hero.subtitle': 'QuokkaAI is the engine that builds, scales and grows your data insights to the next level.',
    'landing.hero.getStarted': 'Start for free',
    'landing.hero.talkToSales': 'Talk to sales',
    
    // Landing page - Stats
    'landing.stats.title': 'The system of action for the next generation.',
    'landing.stats.subtitle': 'QuokkaAI is built for scale. Our customers sort through millions of records with sub-50ms latency.',
    'landing.stats.dataPoints': 'Data points processed',
    'landing.stats.chartTypes': 'Chart types',
    'landing.stats.visualizations': 'Visualizations',
    'landing.stats.uptime': 'Uptime',
    'landing.stats.chartTitle': 'Performance Analytics',
    'landing.stats.dataProcessing': 'Data Processing',
    'landing.stats.querySpeed': 'Query Speed',
    'landing.stats.visualization': 'Visualization',
    'landing.stats.avgResponse': 'Avg Response',
    'landing.stats.throughput': 'Throughput',
    
    // Landing page - Data Sources
    'landing.dataSources.title': 'Connect any type of data',
    'landing.dataSources.subtitle': 'Sync data from databases, files, and APIs for a real-time single source of truth',

    // Landing page - Features
    'features.title': 'Powerful Features',
    'features.subtitle': 'Everything you need to analyze and visualize your data',
    'features.aiAnalysis': 'AI-Powered Analysis',
    'features.aiAnalysisDesc': 'Get intelligent insights from your data with advanced AI algorithms that understand patterns and trends.',
    'features.visualization': 'Smart Visualizations',
    'features.visualizationDesc': 'Create beautiful, interactive charts and graphs automatically from your data with customizable styling.',
    'features.collaboration': 'Real-time Collaboration',
    'features.collaborationDesc': 'Work together with your team in real-time on data analysis projects and share insights instantly.',
    'features.automation': 'Automate everything',
    'features.automationDesc': 'Set up automated workflows to process, analyze, and visualize your data without manual intervention.',
    'features.security': 'Enterprise Security',
    'features.securityDesc': 'Your data is protected with enterprise-grade security, encryption, and compliance standards.',
    'features.integration': 'Easy Integration',
    'features.integrationDesc': 'Connect with 100+ data sources including databases, APIs, and cloud storage platforms.',
    
    // Landing page - How it works
    'howItWorks.title': 'How it works',
    'howItWorks.subtitle': 'Transform your data into actionable insights with our simple three-step process',
    'howItWorks.step1': 'Upload data',
    'howItWorks.step1Desc': 'Connect databases, upload files, or integrate with your existing tools',
    'howItWorks.step2': 'AI processes',
    'howItWorks.step2Desc': 'Our advanced algorithms analyze patterns and extract meaningful insights',
    'howItWorks.step3': 'Get insights',
    'howItWorks.step3Desc': 'Receive beautiful visualizations and actionable reports instantly',
    
    // Landing page - Automation
    'automation.title': 'Automate everything',
    'automation.subtitle': 'Create powerful workflows that run automatically',
    'automation.trigger': 'When data is uploaded',
    'automation.condition': 'If file size > 1MB',
    'automation.action1': 'Clean and process data',
    'automation.action2': 'Generate visualizations',
    'automation.action3': 'Send email report',
    
    // Landing page - Charts showcase
    'charts.title': 'Create any chart instantly',
    'charts.subtitle': 'AI-powered visualization for every data type',
    'charts.salesOverview': 'Sales Overview',
    'charts.revenue': 'Total Revenue',
    'charts.subscriptions': 'Subscriptions',
    'charts.salesByRegion': 'Sales by Region',
    'charts.userDistribution': 'User Distribution',
    'charts.growthTrend': 'Growth Trend',
    'charts.dataPoints': 'Data Points',
    'charts.growth': 'Growth Rate',
    'charts.performance': 'Performance',
    'charts.analytics': 'Analytics',
    'charts.insights': 'Data Insights',
    
    // Landing page - Pricing
    'pricing.title': 'Simple, Transparent Pricing',
    'pricing.subtitle': 'Choose the plan that fits your needs',
    'pricing.free': 'Free',
    'pricing.pro': 'Pro',
    'pricing.enterprise': 'Enterprise',
    'pricing.month': 'month',
    'pricing.letsDiscuss': 'Let\'s discuss',
    'pricing.getStarted': 'Get Started',
    'pricing.contactUs': 'Contact Us',
    'pricing.freeFeatures': '20MB storage, Basic charts, Email support',
    'pricing.proFeatures': '500MB storage, Advanced charts, Priority support, API access',
    'pricing.enterpriseFeatures': 'Unlimited storage, Custom charts, Dedicated support, White-label',
    
    // Landing page - CTA
    'cta.title': 'Ready to transform your data?',
    'cta.subtitle': 'Join thousands of professionals who trust QuokkaAI',
    'cta.getStarted': 'Get Started',
    'cta.talkToSales': 'Talk to Sales',
    
    // Dashboard preview
    'dashboard.title': 'QuokkaAI - Data Analysis Assistant',
    'dashboard.totalChats': 'Total Chats',
    'dashboard.documents': 'Documents',
    'dashboard.activeToday': 'Active Today',
    'dashboard.analyses': 'Analyses',
    'dashboard.newAnalysis': 'New Analysis',
    'dashboard.recentAnalyses': 'Recent Analyses',
    'dashboard.messages': 'messages',
    'dashboard.ready': '👋 Welcome to QuokkaAI! Here you can ask questions and create custom visualizations based on the files you selected.',
    
    // Auth
    'auth.signIn': 'Sign In',
    'auth.signUp': 'Sign Up',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.name': 'Name',
    'auth.confirmPassword': 'Confirm Password',
    'auth.forgotPassword': 'Forgot Password?',
    'auth.noAccount': 'Don\'t have an account?',
    'auth.hasAccount': 'Already have an account?',
    'auth.createAccount': 'Create Account',
    'auth.signInButton': 'Sign In',
    'auth.signUpButton': 'Sign Up',
    'auth.welcomeBack': 'Welcome back',
    'auth.getStarted': 'Get started',
    'auth.signInSubtitle': 'Sign in to continue to your dashboard',
    'auth.signUpSubtitle': 'Create your account to begin analyzing data',
    'auth.processing': 'Processing...',
    'auth.heroTitle': 'Transform your data into intelligent insights',
    'auth.heroDescription': 'Join thousands of professionals who trust quokkaAI to analyze their data and generate beautiful visualizations with the power of artificial intelligence.',
    'auth.feature1': 'Advanced AI-powered analytics',
    'auth.feature2': 'Beautiful data visualizations',
    'auth.feature3': 'Secure and reliable platform',
    'auth.namePlaceholder': 'Enter your full name',
    'auth.emailPlaceholder': 'Enter your email',
    'auth.passwordPlaceholder': 'Enter your password',
    'auth.confirmPasswordPlaceholder': 'Confirm your password',
    
    // OTP Verification
    'otp.verifyEmail': 'Verify Your Email',
    'otp.codeSent': 'We\'ve sent a 6-digit verification code to',
    'otp.enterCode': 'Please enter the complete 6-digit code',
    'otp.codeExpires': 'Code expires in',
    'otp.codeExpired': 'Code has expired',
    'otp.verifying': 'Verifying...',
    'otp.verifyCode': 'Verify Code',
    'otp.didntReceive': 'Didn\'t receive the code?',
    'otp.resend': 'Resend',
    'otp.resendAvailable': 'Resend available in',
    'otp.verificationFailed': 'Verification failed',
    'otp.invalidCode': 'Invalid or expired verification code',
    'otp.resendFailed': 'Failed to resend verification code',
    'otp.sendingCode': 'Sending verification code...',
    
    // Chat
    'chat.welcome': '👋 Welcome to QuokkaAI! Here you can ask questions and create custom visualizations based on the files you selected.',
    'chat.typeMessage': 'Type your message here...',
    'chat.uploadFile': 'Upload file',
    'chat.sendMessage': 'Send message',
    'chat.newThread': 'New Thread',
    'chat.threadCreated': 'New thread created',
    'chat.threadLoaded': 'Thread loaded successfully',
    'chat.uploadingFile': 'Uploading file: {fileName}',
    'chat.analyzeFile': 'Analyze uploaded file: {fileName}',
    'chat.askAnything': 'Ask me anything...',
    'chat.askAnythingData': 'Ask me anything about your data...',
    'chat.files': 'files',
    'chat.showDocuments': 'Show documents',
    'chat.closeDocuments': 'Close documents',
    'chat.fileUploaded': 'File {fileName} uploaded successfully!',
    'chat.fileUploadedCreatingViz': '✅ File {fileName} uploaded! Creating visualization...',
    'chat.fileUploadError': 'File upload error',
    'chat.messageSent': 'Message sent successfully',
    'chat.messageSendError': 'Failed to send message',
    'chat.errorMessage': 'Sorry, I encountered an error while processing your request. Please try again.',
    'chat.threadLoadError': 'Failed to load thread context',
    'chat.threadCreateError': 'Failed to create thread',

    // Start Work Interface
    'startWork.title': 'Welcome to QuokkaAI',
    'startWork.subtitle': 'Your intelligent data analysis assistant',
    'startWork.placeholder': 'Ask me anything about your data...',
    'startWork.placeholderMobile': 'Ask me anything...',
    'startWork.uploadData': 'Upload Data',
    'startWork.uploadDataDesc': 'Upload spreadsheets, PDFs or integrate data sources for analysis.',
    'startWork.askQuestions': 'Ask Questions',
    'startWork.askQuestionsDesc': 'Generate charts, tables, insights, advanced models & more.',
    'startWork.aiAnalysis': 'AI Analysis',
    'startWork.aiAnalysisDesc': 'Execute AI-powered analysis across your data with smart prompts.',
    'startWork.expertHelp': 'Expert Help',
    'startWork.expertHelpDesc': 'Get help with formulas, queries, analysis techniques & more.',
    'startWork.orGetStarted': 'or get started quickly with a',
    'startWork.oneClickTemplate': 'one-click template',
    'startWork.quantitativeAnalysis': 'Quantitative Analysis',
    'startWork.quantitativeDesc': 'Generate tables, charts, insights & more.',
    'startWork.qualitativeAnalysis': 'Qualitative Analysis',
    'startWork.qualitativeDesc': 'Add intelligent columns and insights with AI.',
    'startWork.cleanPrepData': 'Data Processing',
    'startWork.uncoverInsights': 'Uncover Insights',
    'startWork.generateCharts': 'Generate Charts',
    'startWork.identifyCorrelations': 'Identify Correlations',
    'startWork.sentimentAnalysis': 'Sentiment Analysis',
    'startWork.textClassification': 'Text Classification',
    'startWork.extractEntities': 'Extract Entities',
    'startWork.topicModeling': 'Topic Modeling',
    'startWork.footer': 'Powered by advanced AI • Secure & Private • Enterprise Ready',
    'startWork.welcomeBanner': '👋 Welcome to QuokkaAI! To get started:',
    'startWork.uploadTable': 'Upload a table 📁',
    'startWork.clickNewAnalysis': 'Click "New Analysis" ➕',
    'startWork.startAsking': 'Start asking questions 💬',
    
    // Chat welcome message
    'chat.welcomeTitle': '👋 Welcome to QuokkaAI!',
    'chat.welcomeSubtitle': 'Here you can ask questions and create custom visualizations based on the files you selected.',
    
    // Profile
    'profile.accountSettings': 'Account Settings',
    'profile.preferences': 'Preferences',
    'profile.chatHistory': 'Chat History',
    'profile.chartsAnalytics': 'Charts & Analytics',
    'profile.subscription': 'Subscription',
    'profile.personalInfo': 'Personal Information',
    'profile.firstName': 'First Name',
    'profile.lastName': 'Last Name',
    'profile.email': 'Email',
    'profile.phone': 'Phone',
    'profile.company': 'Company',
    'profile.edit': 'Edit',
    'profile.save': 'Save Changes',
    'profile.saving': 'Saving...',
    'profile.cancel': 'Cancel',
    'profile.profileSettings': 'Profile Settings',
    'profile.helpSupport': 'Help & Support',
    'profile.signOut': 'Sign Out',
    'profile.freePlan': 'Free Plan',
    'profile.upgrade': 'Upgrade',
    'profile.queriesRemaining': 'queries remaining',
    
    // Sidebar
    'sidebar.newChat': 'New Chat',
    'sidebar.recentChats': 'Recent Chats',
    'sidebar.profile': 'Profile',
    'sidebar.settings': 'Settings',
    'sidebar.help': 'Help',
    'sidebar.logout': 'Logout',
    
    // Common
    'common.language': 'Language',
    'common.english': 'English',
    'common.russian': 'Russian',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.close': 'Close',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.add': 'Add',
    'common.remove': 'Remove',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.export': 'Export',
    'common.import': 'Import',
    'common.download': 'Download',
    'common.upload': 'Upload',
    'common.share': 'Share',
    'common.copy': 'Copy',
    'common.paste': 'Paste',
    'common.cut': 'Cut',
    'common.undo': 'Undo',
    'common.redo': 'Redo',
    'common.refresh': 'Refresh',
    'common.reload': 'Reload',
    'common.reset': 'Reset',
    'common.clear': 'Clear',
    'common.select': 'Select',
    'common.selectAll': 'Select All',
    'common.deselect': 'Deselect',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.continue': 'Continue',
    'common.finish': 'Finish',
    'common.done': 'Done',
    'common.ok': 'OK',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.maybe': 'Maybe',
    'common.always': 'Always',
    'common.never': 'Never',
    'common.sometimes': 'Sometimes',
    'common.often': 'Often',
    'common.rarely': 'Rarely',
    'common.frequently': 'Frequently',
    'common.occasionally': 'Occasionally',
    'common.dismiss': 'Dismiss',
    
    // Upload
    'upload.uploadDocument': 'Upload Document',
    'upload.fileTypeNotSupported': 'File type {fileExt} not supported. Allowed types: {allowedTypes}',
    'upload.fileTooLarge': 'File too large. Maximum size is 50MB',
    'upload.documentUploaded': 'Document uploaded successfully',
    'upload.uploadFailed': 'Failed to upload document',
    'upload.uploadError': 'Error uploading document',
    'upload.dropFileHere': 'Drop your file here',
    'upload.dragDropFile': 'Drag and drop your file here',
    'upload.orClickBrowse': 'or click to browse files',
    'upload.supportedFormats': 'Supported: CSV, Excel, PDF, JSON, TXT, MD',
    'upload.maxSize': 'Maximum size: 50MB',
    'upload.tagsOptional': 'Tags (optional)',
    'upload.tagsPlaceholder': 'e.g., finance, quarterly, report',
    'upload.tagsHelp': 'Separate multiple tags with commas',
    'upload.uploading': 'Uploading...',
    'upload.uploadFile': 'Upload File',
    
    // Documents
    'documents.documentContext': 'Document Context',
    'documents.documentsSelected': '{count} document{count === 1 ? "" : "s"} selected',
    'documents.uploadDocuments': 'Upload Documents',
    'documents.noDocuments': 'No documents selected',
    'documents.uploadToStart': 'Upload documents to get started',
    'documents.confirmDelete': 'Are you sure you want to delete this document?',
    'documents.deleteFailed': 'Failed to delete document',
    'documents.deleteDocument': 'Delete document',
    'documents.clickToView': 'Click on any document to view its content',
    'documents.chunks': '{count} chunks',
    'documents.0Bytes': '0 Bytes',
    'documents.bytes': 'Bytes',
    'documents.kb': 'KB',
    'documents.mb': 'MB',
    'documents.gb': 'GB',
    
    // Document Viewer
    'documents.loading': 'Loading document...',
    'documents.loadError': 'Failed to load document',
    'documents.pdfLoadError': 'Failed to load PDF',
    'documents.pdfCorrupted': 'The PDF file might be corrupted or unsupported',
    'documents.loadingPdf': 'Loading PDF...',
    'documents.pageLoadError': 'Failed to load page',
    'documents.previousPage': 'Previous page',
    'documents.nextPage': 'Next page',
    'documents.pageOf': 'Page {current} of {total}',
    'documents.documentContent': 'Document Content',
    'documents.textContent': 'Text Content',
    'documents.column': 'Column',
    'documents.noDataInSheet': 'No data found in this sheet',
    'documents.sheet': 'Sheet',
    'documents.tableSize': '{rows} rows × {cols} columns',
    'documents.documentInfo': 'Document Info',
    'documents.fileName': 'File Name',
    'documents.fileType': 'File Type',
    'documents.fileSize': 'File Size',
    'documents.uploaded': 'Uploaded',
    'documents.summary': 'Summary',
    
    // Data Cleaning
    'dataCleaning.title': 'Clean up your data',
    'dataCleaning.description': 'Remove duplicates, handle missing values, and standardize your data format',
    'dataCleaning.uploadFile': 'Upload File',
    'dataCleaning.dropFileHere': 'Drop your file here',
    'dataCleaning.orClickToBrowse': 'or click to browse',
    'dataCleaning.selectFile': 'Select File',
    'dataCleaning.supportedFormats': 'Supported formats: CSV, Excel (.xlsx, .xls)',
    'dataCleaning.mb': 'MB',
    'dataCleaning.selectOperations': 'Select Operations',
    'dataCleaning.dataCleanedSuccessfully': 'Data cleaned successfully',
    'dataCleaning.dataProcessedReady': 'Your data has been processed and is ready for download',
    'dataCleaning.downloadCleanedFile': 'Download Cleaned File',
    'dataCleaning.addToDocuments': 'Add to Documents',
    'dataCleaning.cancel': 'Cancel',
    'dataCleaning.cleaningFailed': 'Cleaning failed',
    'dataCleaning.errorProcessingData': 'An error occurred while processing your data',
    'dataCleaning.processing': 'Processing...',
    'dataCleaning.cleanData': 'Clean Data',
    
    // Data Cleaning Operations
    'dataCleaning.removeDuplicates': 'Remove Duplicates',
    'dataCleaning.removeDuplicatesDesc': 'Remove duplicate rows from your dataset',
    'dataCleaning.handleMissing': 'Handle Missing Values',
    'dataCleaning.handleMissingDesc': 'Fill or remove missing values in your data',
    'dataCleaning.standardizeFormat': 'Standardize Format',
    'dataCleaning.standardizeFormatDesc': 'Standardize data formats and types',
    
    // Document Selection Modal
    'documentSelection.title': 'Select Documents',
    'documentSelection.description': 'Choose documents to include in your analysis',
    'documentSelection.files': 'Files',
    'documentSelection.dataSources': 'Data Sources',
    'documentSelection.enrichments': 'Enrichments',
    'documentSelection.searchFiles': 'Search files',
    'documentSelection.uploadFiles': 'Upload files',
    'documentSelection.uploadGoogleSheets': 'Upload Google Sheets',
    'documentSelection.noDocumentsFound': 'No documents found',
    'documentSelection.uploadFirstDocument': 'Upload your first document to get started',
    'documentSelection.uploadDocument': 'Upload Document',
    'documentSelection.deleteDocument': 'Delete document',
    'documentSelection.confirmDelete': 'Are you sure you want to delete this document?',
    'documentSelection.filesSelected': '{count} file{count === 1 ? "" : "s"} selected',
    'documentSelection.cancel': 'Cancel',
    'documentSelection.confirmSelection': 'Confirm selection',
    'documentSelection.uploading': 'Uploading...',
    
    // Thread Chatbot
    'threadChatbot.selectDocumentsForChat': 'Select Documents for this Chat',
    'threadChatbot.loadingDocuments': 'Loading documents...',
    'threadChatbot.noDocumentsUploaded': 'No documents uploaded yet. Upload documents in the old chatbot interface to use them here.',
    'threadChatbot.welcomeTitle': 'Welcome to QuokkaAI',
    'threadChatbot.welcomeDescription': 'Your intelligent data analysis assistant with thread-based conversations',
    'threadChatbot.welcomeSubtext': 'Select a chat from the sidebar or create a new one to get started',
    'threadChatbot.startConversation': 'Start the conversation by sending a message below',
    'threadChatbot.messagesCount': '{count} messages',
    'threadChatbot.documentsSelected': '{count} documents selected',
    'threadChatbot.selectChatOrStart': 'Select a chat or start a new conversation',
    'threadChatbot.logout': 'Logout',
    'threadChatbot.backToLanding': 'Back to Landing',
    'threadChatbot.documents': 'Documents',
    'threadChatbot.typeMessage': 'Type your message...',
    'threadChatbot.visualization': 'Visualization',
    'threadChatbot.visualizationAvailable': 'Visualization available',
    'threadChatbot.confidence': 'Confidence: {percent}%',
     'threadChatbot.dismiss': 'Dismiss',
     'threadChatbot.chunks': 'chunks',
     
     // Main content
     'mainContent.analyzeToday': 'What do you want to analyze today?',
     'mainContent.welcomeBack': 'Welcome back, {name}! Ready to dive into your data?',
     'mainContent.default': 'Default',
     'mainContent.tools': 'Tools',
     'mainContent.advancedReasoning': 'Advanced Reasoning',
     'mainContent.extendedMemory': 'Extended Memory',
     'mainContent.welcomeToQuokka': 'Welcome to QuokkaAI',
     'mainContent.welcomeDescription': 'Feel free to upload your data files and start your analytical work! I\'m here to help you visualize, analyze, and understand your data through intelligent conversations.',
     'mainContent.chatPlaceholder': 'Upload your data and start chatting! Try: \'Upload my sales data and create a visualization\'',
     'mainContent.proTip': 'Pro tip: You can upload files directly in the chat or drag & drop them here',
     'mainContent.supportedFormats': 'Supported formats: CSV, Excel, PDF, TXT, DOCX',
     
     // Workspace layout
     'workspaceLayout.noAnalysesYet': 'No analyses yet',
     'workspaceLayout.createFirstAnalysis': 'Create your first analysis to get started',
     'workspaceLayout.noDocumentsYet': 'No documents yet',
     'workspaceLayout.uploadFilesToStart': 'Upload files to start analyzing',
     'workspaceLayout.moreFiles': '+{count} more files',
  },
  ru: {
    // Navigation
    'nav.features': 'Возможности',
    'nav.howItWorks': 'Как это работает',
    'nav.pricing': 'Цены',
    'nav.signIn': 'Войти',
    'nav.startForFree': 'Начать бесплатно',
    'nav.back': 'Назад',
    
    // Landing page - Hero
    'landing.hero.title': 'Новое поколение анализа данных.',
    'landing.hero.subtitle': 'QuokkaAI — это движок, который создает, масштабирует и развивает ваши инсайты данных на новый уровень.',
    'landing.hero.getStarted': 'Начать бесплатно',
    'landing.hero.talkToSales': 'Связаться с продажами',
    
    // Landing page - Stats
    'landing.stats.title': 'Система действий для нового поколения.',
    'landing.stats.subtitle': 'QuokkaAI создан для масштаба. Наши клиенты обрабатывают миллионы записей с задержкой менее 50мс.',
    'landing.stats.dataPoints': 'Обработано точек данных',
    'landing.stats.chartTypes': 'Типов графиков',
    'landing.stats.visualizations': 'Визуализаций',
    'landing.stats.uptime': 'Время работы',
    'landing.stats.chartTitle': 'Аналитика производительности',
    'landing.stats.dataProcessing': 'Обработка данных',
    'landing.stats.querySpeed': 'Скорость запросов',
    'landing.stats.visualization': 'Визуализация',
    'landing.stats.avgResponse': 'Среднее время отклика',
    'landing.stats.throughput': 'Пропускная способность',
    
    // Landing page - Data Sources
    'landing.dataSources.title': 'Подключите любые типы данных',
    'landing.dataSources.subtitle': 'Синхронизируйте данные из баз данных, файлов и API для единого источника правды в реальном времени',
    
    // Landing page - Features
    'features.title': 'Мощные возможности',
    'features.subtitle': 'Все что нужно для анализа и визуализации ваших данных',
    'features.aiAnalysis': 'ИИ-анализ',
    'features.aiAnalysisDesc': 'Получайте интеллектуальные инсайты из ваших данных с помощью продвинутых алгоритмов ИИ, которые понимают паттерны и тренды.',
    'features.visualization': 'Умная визуализация',
    'features.visualizationDesc': 'Создавайте красивые интерактивные графики и диаграммы автоматически из ваших данных с настраиваемым стилем.',
    'features.collaboration': 'Совместная работа в реальном времени',
    'features.collaborationDesc': 'Работайте с командой в реальном времени над проектами анализа данных и мгновенно делитесь инсайтами.',
    'features.automation': 'Автоматизируйте все',
    'features.automationDesc': 'Настройте автоматизированные рабочие процессы для обработки, анализа и визуализации данных без ручного вмешательства.',
    'features.security': 'Корпоративная безопасность',
    'features.securityDesc': 'Ваши данные защищены корпоративной безопасностью, шифрованием и стандартами соответствия.',
    'features.integration': 'Простая интеграция',
    'features.integrationDesc': 'Подключайтесь к 100+ источникам данных включая базы данных, API и облачные платформы хранения.',
    
    // Landing page - How it works
    'howItWorks.title': 'Как это работает',
    'howItWorks.subtitle': 'Превратите ваши данные в действенные инсайты с помощью нашего простого трёхэтапного процесса',
    'howItWorks.step1': 'Загрузите данные',
    'howItWorks.step1Desc': 'Подключите базы данных, загрузите файлы или интегрируйтесь с существующими инструментами',
    'howItWorks.step2': 'ИИ обрабатывает',
    'howItWorks.step2Desc': 'Наши продвинутые алгоритмы анализируют паттерны и извлекают значимые инсайты',
    'howItWorks.step3': 'Получите инсайты',
    'howItWorks.step3Desc': 'Получайте красивые визуализации и действенные отчёты мгновенно',
    
    // Landing page - Automation
    'automation.title': 'Автоматизируйте все',
    'automation.subtitle': 'Создавайте мощные рабочие процессы, которые работают автоматически',
    'automation.trigger': 'Когда данные загружены',
    'automation.condition': 'Если размер файла > 1МБ',
    'automation.action1': 'Очистить и обработать данные',
    'automation.action2': 'Создать визуализации',
    'automation.action3': 'Отправить отчет по email',
    
    // Landing page - Charts showcase
    'charts.title': 'Создавайте любые графики мгновенно',
    'charts.subtitle': 'ИИ-визуализация для любого типа данных',
    'charts.salesOverview': 'Обзор продаж',
    'charts.revenue': 'Общий доход',
    'charts.subscriptions': 'Подписки',
    'charts.salesByRegion': 'Продажи по регионам',
    'charts.userDistribution': 'Распределение пользователей',
    'charts.growthTrend': 'Тренд роста',
    'charts.dataPoints': 'Точки данных',
    'charts.growth': 'Темп роста',
    'charts.performance': 'Производительность',
    'charts.analytics': 'Аналитика',
    'charts.insights': 'Инсайты данных',
    
    // Landing page - Pricing
    'pricing.title': 'Простые, прозрачные цены',
    'pricing.subtitle': 'Выберите план, который подходит вашим потребностям',
    'pricing.free': 'Бесплатно',
    'pricing.pro': 'Про',
    'pricing.enterprise': 'Корпоративный',
    'pricing.month': 'месяц',
    'pricing.letsDiscuss': 'Обсудим',
    'pricing.getStarted': 'Начать',
    'pricing.contactUs': 'Связаться с нами',
    'pricing.freeFeatures': '20МБ хранилище, Базовые графики, Email поддержка',
    'pricing.proFeatures': '500МБ хранилище, Продвинутые графики, Приоритетная поддержка, API доступ',
    'pricing.enterpriseFeatures': 'Безлимитное хранилище, Кастомные графики, Выделенная поддержка, White-label',
    
    // Landing page - CTA
    'cta.title': 'Готовы трансформировать ваши данные?',
    'cta.subtitle': 'Присоединяйтесь к тысячам профессионалов, которые доверяют QuokkaAI',
    'cta.getStarted': 'Начать',
    'cta.talkToSales': 'Связаться с продажами',
    
    // Dashboard preview
    'dashboard.title': 'QuokkaAI - Ассистент анализа данных',
    'dashboard.totalChats': 'Всего чатов',
    'dashboard.documents': 'Документы',
    'dashboard.activeToday': 'Активных сегодня',
    'dashboard.analyses': 'Анализы',
    'dashboard.newAnalysis': 'Новый анализ',
    'dashboard.recentAnalyses': 'Недавние анализы',
    'dashboard.messages': 'сообщений',
    'dashboard.ready': '👋 Привет! Добро пожаловать в QuokkaAI! Здесь ты можешь задавать вопросы и создавать кастомные визуализации по файлам, которые ты выбрал.',
    
    // Auth
    'auth.signIn': 'Войти',
    'auth.signUp': 'Регистрация',
    'auth.email': 'Email',
    'auth.password': 'Пароль',
    'auth.name': 'Имя',
    'auth.confirmPassword': 'Подтвердите пароль',
    'auth.forgotPassword': 'Забыли пароль?',
    'auth.noAccount': 'Нет аккаунта?',
    'auth.hasAccount': 'Уже есть аккаунт?',
    'auth.createAccount': 'Создать аккаунт',
    'auth.signInButton': 'Войти',
    'auth.signUpButton': 'Зарегистрироваться',
    'auth.welcomeBack': 'С возвращением',
    'auth.getStarted': 'Начать',
    'auth.signInSubtitle': 'Войдите, чтобы продолжить в панель управления',
    'auth.signUpSubtitle': 'Создайте аккаунт, чтобы начать анализировать данные',
    'auth.processing': 'Обработка...',
    'auth.heroTitle': 'Превратите ваши данные в интеллектуальные инсайты',
    'auth.heroDescription': 'Присоединяйтесь к тысячам профессионалов, которые доверяют quokkaAI анализировать свои данные и создавать красивые визуализации с помощью искусственного интеллекта.',
    'auth.feature1': 'Продвинутая аналитика на основе ИИ',
    'auth.feature2': 'Красивые визуализации данных',
    'auth.feature3': 'Безопасная и надёжная платформа',
    'auth.namePlaceholder': 'Введите ваше полное имя',
    'auth.emailPlaceholder': 'Введите ваш email',
    'auth.passwordPlaceholder': 'Введите ваш пароль',
    'auth.confirmPasswordPlaceholder': 'Подтвердите ваш пароль',
    
    // OTP Verification
    'otp.verifyEmail': 'Подтвердите ваш email',
    'otp.codeSent': 'Мы отправили 6-значный код подтверждения на',
    'otp.enterCode': 'Пожалуйста, введите полный 6-значный код',
    'otp.codeExpires': 'Код истекает через',
    'otp.codeExpired': 'Код истек',
    'otp.verifying': 'Проверка...',
    'otp.verifyCode': 'Подтвердить код',
    'otp.didntReceive': 'Не получили код?',
    'otp.resend': 'Отправить повторно',
    'otp.resendAvailable': 'Повторная отправка доступна через',
    'otp.verificationFailed': 'Проверка не удалась',
    'otp.invalidCode': 'Неверный или истекший код подтверждения',
    'otp.resendFailed': 'Не удалось отправить код повторно',
    'otp.sendingCode': 'Отправка кода подтверждения...',
    
    // Chat
    'chat.welcome': '👋 Привет! Добро пожаловать в QuokkaAI! Здесь ты можешь задавать вопросы и создавать кастомные визуализации по файлам, которые ты выбрал.',
    'chat.typeMessage': 'Введите ваше сообщение...',
    'chat.uploadFile': 'Загрузить файл',
    'chat.sendMessage': 'Отправить сообщение',
    'chat.newThread': 'Новый диалог',
    'chat.threadCreated': 'Новый диалог создан',
    'chat.threadLoaded': 'Диалог загружен успешно',
    'chat.uploadingFile': 'Загружаю файл: {fileName}',
    'chat.analyzeFile': 'Анализирую загруженный файл: {fileName}',
    'chat.askAnything': 'Спросите что угодно...',
    'chat.askAnythingData': 'Спросите что угодно о ваших данных...',
    'chat.files': 'файлов',
    'chat.showDocuments': 'Показать документы',
    'chat.closeDocuments': 'Закрыть документы',
    'chat.fileUploaded': 'Файл {fileName} загружен успешно!',
    'chat.fileUploadedCreatingViz': '✅ Файл {fileName} загружен! Создаю визуализацию...',
    'chat.fileUploadError': 'Ошибка загрузки файла',
    'chat.messageSent': 'Сообщение отправлено успешно',
    'chat.messageSendError': 'Не удалось отправить сообщение',
    'chat.errorMessage': 'Извините, произошла ошибка при обработке вашего запроса. Пожалуйста, попробуйте еще раз.',
    'chat.threadLoadError': 'Не удалось загрузить контекст диалога',
    'chat.threadCreateError': 'Не удалось создать диалог',

    // Start Work Interface
    'startWork.title': 'Добро пожаловать в QuokkaAI',
    'startWork.subtitle': 'Ваш интеллектуальный помощник по анализу данных',
    'startWork.placeholder': 'Спросите что угодно о ваших данных...',
    'startWork.placeholderMobile': 'Спросите что угодно...',
    'startWork.uploadData': 'Загрузить данные',
    'startWork.uploadDataDesc': 'Загрузите таблицы, PDF или интегрируйте источники данных для анализа.',
    'startWork.askQuestions': 'Задать вопросы',
    'startWork.askQuestionsDesc': 'Генерируйте графики, таблицы, инсайты, продвинутые модели и многое другое.',
    'startWork.aiAnalysis': 'ИИ-анализ',
    'startWork.aiAnalysisDesc': 'Выполняйте анализ на основе ИИ по вашим данным с умными подсказками.',
    'startWork.expertHelp': 'Помощь эксперта',
    'startWork.expertHelpDesc': 'Получите помощь с формулами, запросами, техниками анализа и многим другим.',
    'startWork.orGetStarted': 'или быстро начните с',
    'startWork.oneClickTemplate': 'шаблона в один клик',
    'startWork.quantitativeAnalysis': 'Количественный анализ',
    'startWork.quantitativeDesc': 'Генерируйте таблицы, графики, инсайты и многое другое.',
    'startWork.qualitativeAnalysis': 'Качественный анализ',
    'startWork.qualitativeDesc': 'Добавляйте интеллектуальные колонки и инсайты с помощью ИИ.',
    'startWork.cleanPrepData': 'Обработка данных',
    'startWork.uncoverInsights': 'Найти инсайты',
    'startWork.generateCharts': 'Создать графики',
    'startWork.identifyCorrelations': 'Найти корреляции',
    'startWork.sentimentAnalysis': 'Анализ тональности',
    'startWork.textClassification': 'Классификация текста',
    'startWork.extractEntities': 'Извлечь сущности',
    'startWork.topicModeling': 'Моделирование тем',
    'startWork.footer': 'Работает на продвинутом ИИ • Безопасно и конфиденциально • Готово для предприятий',
    'startWork.welcomeBanner': '👋 Добро пожаловать в QuokkaAI! Чтобы начать:',
    'startWork.uploadTable': 'Загрузите таблицу 📁',
    'startWork.clickNewAnalysis': 'Нажмите "Новый анализ" ➕',
    'startWork.startAsking': 'Начните задавать вопросы 💬',
    
    // Chat welcome message
    'chat.welcomeTitle': '👋 Привет! Добро пожаловать в QuokkaAI!',
    'chat.welcomeSubtitle': 'Здесь ты можешь задавать вопросы и создавать кастомные визуализации по файлам, которые ты выбрал.',
    
    // Profile
    'profile.accountSettings': 'Настройки аккаунта',
    'profile.preferences': 'Предпочтения',
    'profile.chatHistory': 'История чатов',
    'profile.chartsAnalytics': 'Графики и аналитика',
    'profile.subscription': 'Подписка',
    'profile.personalInfo': 'Личная информация',
    'profile.firstName': 'Имя',
    'profile.lastName': 'Фамилия',
    'profile.email': 'Email',
    'profile.phone': 'Телефон',
    'profile.company': 'Компания',
    'profile.edit': 'Редактировать',
    'profile.save': 'Сохранить изменения',
    'profile.saving': 'Сохранение...',
    'profile.cancel': 'Отмена',
    'profile.profileSettings': 'Настройки профиля',
    'profile.helpSupport': 'Помощь и поддержка',
    'profile.signOut': 'Выйти',
    'profile.freePlan': 'Бесплатный план',
    'profile.upgrade': 'Обновить',
    'profile.queriesRemaining': 'запросов осталось',
    
    // Sidebar
    'sidebar.newChat': 'Новый чат',
    'sidebar.recentChats': 'Недавние чаты',
    'sidebar.profile': 'Профиль',
    'sidebar.settings': 'Настройки',
    'sidebar.help': 'Помощь',
    'sidebar.logout': 'Выйти',
    
    // Common
    'common.language': 'Язык',
    'common.english': 'Английский',
    'common.russian': 'Русский',
    'common.loading': 'Загрузка...',
    'common.error': 'Ошибка',
    'common.success': 'Успех',
    'common.close': 'Закрыть',
    'common.save': 'Сохранить',
    'common.cancel': 'Отмена',
    'common.delete': 'Удалить',
    'common.edit': 'Редактировать',
    'common.add': 'Добавить',
    'common.remove': 'Удалить',
    'common.search': 'Поиск',
    'common.filter': 'Фильтр',
    'common.sort': 'Сортировка',
    'common.export': 'Экспорт',
    'common.import': 'Импорт',
    'common.download': 'Скачать',
    'common.upload': 'Загрузить',
    'common.share': 'Поделиться',
    'common.copy': 'Копировать',
    'common.paste': 'Вставить',
    'common.cut': 'Вырезать',
    'common.undo': 'Отменить',
    'common.redo': 'Повторить',
    'common.refresh': 'Обновить',
    'common.reload': 'Перезагрузить',
    'common.reset': 'Сбросить',
    'common.clear': 'Очистить',
    'common.select': 'Выбрать',
    'common.selectAll': 'Выбрать все',
    'common.deselect': 'Отменить выбор',
    'common.next': 'Далее',
    'common.previous': 'Назад',
    'common.continue': 'Продолжить',
    'common.finish': 'Завершить',
    'common.done': 'Готово',
    'common.ok': 'ОК',
    'common.yes': 'Да',
    'common.no': 'Нет',
    'common.maybe': 'Возможно',
    'common.always': 'Всегда',
    'common.never': 'Никогда',
    'common.sometimes': 'Иногда',
    'common.often': 'Часто',
    'common.rarely': 'Редко',
    'common.frequently': 'Часто',
    'common.occasionally': 'Время от времени',
    'common.dismiss': 'Скрыть',
    
    // Upload
    'upload.uploadDocument': 'Загрузить документ',
    'upload.fileTypeNotSupported': 'Тип файла {fileExt} не поддерживается. Разрешенные типы: {allowedTypes}',
    'upload.fileTooLarge': 'Файл слишком большой. Максимальный размер 50МБ',
    'upload.documentUploaded': 'Документ загружен успешно',
    'upload.uploadFailed': 'Не удалось загрузить документ',
    'upload.uploadError': 'Ошибка загрузки документа',
    'upload.dropFileHere': 'Перетащите файл сюда',
    'upload.dragDropFile': 'Перетащите файл сюда',
    'upload.orClickBrowse': 'или нажмите для выбора файлов',
    'upload.supportedFormats': 'Поддерживаемые: CSV, Excel, PDF, JSON, TXT, MD',
    'upload.maxSize': 'Максимальный размер: 50МБ',
    'upload.tagsOptional': 'Теги (необязательно)',
    'upload.tagsPlaceholder': 'например: финансы, квартальный, отчет',
    'upload.tagsHelp': 'Разделяйте несколько тегов запятыми',
    'upload.uploading': 'Загрузка...',
    'upload.uploadFile': 'Загрузить файл',
    
    // Documents
    'documents.documentContext': 'Контекст документов',
    'documents.documentsSelected': '{count} документ{count === 1 ? "" : count < 5 ? "а" : "ов"} выбрано',
    'documents.uploadDocuments': 'Загрузить документы',
    'documents.noDocuments': 'Документы не выбраны',
    'documents.uploadToStart': 'Загрузите документы для начала работы',
    'documents.confirmDelete': 'Вы уверены, что хотите удалить этот документ?',
    'documents.deleteFailed': 'Не удалось удалить документ',
    'documents.deleteDocument': 'Удалить документ',
    'documents.clickToView': 'Нажмите на любой документ для просмотра содержимого',
    'documents.chunks': '{count} частей',
    'documents.0Bytes': '0 Байт',
    'documents.bytes': 'Байт',
    'documents.kb': 'КБ',
    'documents.mb': 'МБ',
    'documents.gb': 'ГБ',
    
    // Document Viewer
    'documents.loading': 'Загрузка документа...',
    'documents.loadError': 'Не удалось загрузить документ',
    'documents.pdfLoadError': 'Не удалось загрузить PDF',
    'documents.pdfCorrupted': 'PDF файл может быть поврежден или не поддерживается',
    'documents.loadingPdf': 'Загрузка PDF...',
    'documents.pageLoadError': 'Не удалось загрузить страницу',
    'documents.previousPage': 'Предыдущая страница',
    'documents.nextPage': 'Следующая страница',
    'documents.pageOf': 'Страница {current} из {total}',
    'documents.documentContent': 'Содержимое документа',
    'documents.textContent': 'Текстовое содержимое',
    'documents.column': 'Колонка',
    'documents.noDataInSheet': 'Данные в этом листе не найдены',
    'documents.sheet': 'Лист',
    'documents.tableSize': '{rows} строк × {cols} столбцов',
    'documents.documentInfo': 'Информация о документе',
    'documents.fileName': 'Имя файла',
    'documents.fileType': 'Тип файла',
    'documents.fileSize': 'Размер файла',
    'documents.uploaded': 'Загружено',
    'documents.summary': 'Сводка',
    
    // Data Cleaning
    'dataCleaning.title': 'Очистка данных',
    'dataCleaning.description': 'Удаление дубликатов, обработка пропущенных значений и стандартизация формата данных',
    'dataCleaning.uploadFile': 'Загрузить файл',
    'dataCleaning.dropFileHere': 'Перетащите файл сюда',
    'dataCleaning.orClickToBrowse': 'или нажмите для выбора',
    'dataCleaning.selectFile': 'Выбрать файл',
    'dataCleaning.supportedFormats': 'Поддерживаемые форматы: CSV, Excel (.xlsx, .xls)',
    'dataCleaning.mb': 'МБ',
    'dataCleaning.selectOperations': 'Выберите операции',
    'dataCleaning.dataCleanedSuccessfully': 'Данные успешно очищены',
    'dataCleaning.dataProcessedReady': 'Ваши данные обработаны и готовы для скачивания',
    'dataCleaning.downloadCleanedFile': 'Скачать очищенный файл',
    'dataCleaning.addToDocuments': 'Добавить в документы',
    'dataCleaning.cancel': 'Отмена',
    'dataCleaning.cleaningFailed': 'Очистка не удалась',
    'dataCleaning.errorProcessingData': 'Произошла ошибка при обработке ваших данных',
    'dataCleaning.processing': 'Обработка...',
    'dataCleaning.cleanData': 'Очистить данные',
    
    // Data Cleaning Operations
    'dataCleaning.removeDuplicates': 'Удалить дубликаты',
    'dataCleaning.removeDuplicatesDesc': 'Удалить дублирующиеся строки из вашего набора данных',
    'dataCleaning.handleMissing': 'Обработать пропущенные значения',
    'dataCleaning.handleMissingDesc': 'Заполнить или удалить пропущенные значения в ваших данных',
    'dataCleaning.standardizeFormat': 'Стандартизировать формат',
    'dataCleaning.standardizeFormatDesc': 'Стандартизировать форматы и типы данных',
    
    // Document Selection Modal
    'documentSelection.title': 'Выбрать документы',
    'documentSelection.description': 'Выберите документы для включения в ваш анализ',
    'documentSelection.files': 'Файлы',
    'documentSelection.dataSources': 'Источники данных',
    'documentSelection.enrichments': 'Обогащения',
    'documentSelection.searchFiles': 'Поиск файлов',
    'documentSelection.uploadFiles': 'Загрузить файлы',
    'documentSelection.uploadGoogleSheets': 'Загрузить Google Таблицы',
    'documentSelection.noDocumentsFound': 'Документы не найдены',
    'documentSelection.uploadFirstDocument': 'Загрузите ваш первый документ для начала работы',
    'documentSelection.uploadDocument': 'Загрузить документ',
    'documentSelection.deleteDocument': 'Удалить документ',
    'documentSelection.confirmDelete': 'Вы уверены, что хотите удалить этот документ?',
    'documentSelection.filesSelected': '{count} файл{count === 1 ? "" : count < 5 ? "а" : "ов"} выбрано',
    'documentSelection.cancel': 'Отмена',
    'documentSelection.confirmSelection': 'Подтвердить выбор',
    'documentSelection.uploading': 'Загрузка...',
    
    // Thread Chatbot
    'threadChatbot.selectDocumentsForChat': 'Выбрать документы для этого чата',
    'threadChatbot.loadingDocuments': 'Загрузка документов...',
    'threadChatbot.noDocumentsUploaded': 'Документы еще не загружены. Загрузите документы в старом интерфейсе чатбота, чтобы использовать их здесь.',
    'threadChatbot.welcomeTitle': 'Добро пожаловать в QuokkaAI',
    'threadChatbot.welcomeDescription': 'Ваш интеллектуальный помощник по анализу данных с диалогами на основе потоков',
    'threadChatbot.welcomeSubtext': 'Выберите чат из боковой панели или создайте новый для начала работы',
    'threadChatbot.startConversation': 'Начните разговор, отправив сообщение ниже',
    'threadChatbot.messagesCount': '{count} сообщений',
    'threadChatbot.documentsSelected': '{count} документов выбрано',
    'threadChatbot.selectChatOrStart': 'Выберите чат или начните новый разговор',
    'threadChatbot.logout': 'Выйти',
    'threadChatbot.backToLanding': 'Вернуться на главную',
    'threadChatbot.documents': 'Документы',
    'threadChatbot.typeMessage': 'Введите ваше сообщение...',
    'threadChatbot.visualization': 'Визуализация',
    'threadChatbot.visualizationAvailable': 'Визуализация доступна',
    'threadChatbot.confidence': 'Уверенность: {percent}%',
    'threadChatbot.dismiss': 'Скрыть',
    'threadChatbot.chunks': 'частей',
    
    // Main Content
    'mainContent.whatAnalyze': 'Что вы хотите проанализировать сегодня?',
    'mainContent.welcomeBack': 'С возвращением, {name}! Готовы погрузиться в ваши данные?',
    'mainContent.default': 'По умолчанию',
    'mainContent.tools': 'Инструменты',
    'mainContent.advancedReasoning': 'Продвинутое рассуждение',
    'mainContent.extendedMemory': 'Расширенная память',
    'mainContent.welcomeToQuokka': 'Добро пожаловать в QuokkaAI',
    'mainContent.welcomeDescription': 'Не стесняйтесь загружать ваши файлы данных и начинайте аналитическую работу! Я здесь, чтобы помочь вам визуализировать, анализировать и понимать ваши данные через интеллектуальные диалоги.',
    'mainContent.uploadAndChat': 'Загрузите ваши данные и начните общение! Попробуйте: "Загрузи мои данные продаж и создай визуализацию"',
    'mainContent.proTip': 'Совет: Вы можете загружать файлы прямо в чате или перетаскивать их сюда',
    'mainContent.supportedFormats': 'Поддерживаемые форматы: CSV, Excel, PDF, TXT, DOCX',
    
    // Workspace Layout
    'workspaceLayout.noAnalyses': 'Анализов пока нет',
    'workspaceLayout.createFirstAnalysis': 'Создайте ваш первый анализ для начала работы',
    'workspaceLayout.messages': 'сообщений',
    'workspaceLayout.noDocuments': 'Документов пока нет',
    'workspaceLayout.uploadToStart': 'Загрузите файлы для начала анализа',
    'workspaceLayout.moreFiles': '+{count} файлов больше',
  }
}

export const useLanguageStore = create<LanguageState>()(
  persist(
    (set, get) => ({
      language: 'en',
      
      setLanguage: (lang: Language) => {
        set({ language: lang })
      },
      
      t: (key: string, params?: Record<string, string>) => {
        const { language } = get()
        let translation = (translations[language] as Record<string, string>)[key] || key
        
        // Replace parameters if provided
        if (params) {
          Object.entries(params).forEach(([param, value]) => {
            translation = translation.replace(`{${param}}`, value)
          })
        }
        
        return translation
      }
    }),
    {
      name: 'quokka-language-storage',
      storage: createJSONStorage(() => localStorage),
    }
  )
)